# scale-normalize-methods-python

In [28]:
import numpy as np

In [29]:
# genrate 10 random numbers between 0 and 100
# imagine that is the age of people
rng = np.random.default_rng(12345)
ages = rng.integers(low=0, high=100, size=10)
ages

array([69, 22, 78, 31, 20, 79, 64, 67, 98, 39], dtype=int64)

In [30]:
# genrate 10 random numbers between 100.000 and 1.000.000
# imagine that is the salaries of people
rng = np.random.default_rng(54321)
salaries = rng.integers(low=100000, high=1000000, size=10)
salaries

array([128274, 735383, 916188, 853414, 681216, 527315, 709122, 129701,
       467590, 517491], dtype=int64)

## Simple feature scalling

xnew = xold / xmax

In [31]:
originalages = ages
ages = ages / ages.max()
print(originalages,"\n\n", ages)

[69 22 78 31 20 79 64 67 98 39] 

 [0.70408163 0.2244898  0.79591837 0.31632653 0.20408163 0.80612245
 0.65306122 0.68367347 1.         0.39795918]


In [32]:
originalsalaries = salaries
salaries = salaries / salaries.max()
print(originalsalaries,"\n\n", salaries)

[128274 735383 916188 853414 681216 527315 709122 129701 467590 517491] 

 [0.14000838 0.80265513 1.         0.93148349 0.74353299 0.57555327
 0.7739918  0.14156592 0.51036468 0.56483058]


## Min-Max
###### https://docs.google.com/document/d/1QNIdtduvwepL1N6RB-KwHt7-ymDFq6w51ZvzNXGHVj8/edit

xnew = (xold-xmin)/(xmax-xmin)

In [33]:
ages = originalages
ages = (ages-ages.min()) / (ages.max()-ages.min())
print(originalages,"\n\n", ages)

[69 22 78 31 20 79 64 67 98 39] 

 [0.62820513 0.02564103 0.74358974 0.14102564 0.         0.75641026
 0.56410256 0.6025641  1.         0.24358974]


In [34]:
salaries = originalsalaries
salaries = (salaries-salaries.min()) / (salaries.max()-salaries.min())
print(originalsalaries,"\n\n", salaries)

[128274 735383 916188 853414 681216 527315 709122 129701 467590 517491] 

 [0.         0.77052699 1.         0.92032887 0.70177964 0.50645248
 0.73719721 0.00181111 0.43065106 0.49398412]


## z-score
