# <a id='toc1_'></a>[Numpy](#toc0_)

In [2]:
import numpy as np

## <a id='toc1_1_'></a>[Create arrays](#toc0_)
###### <a id='toc1_1_1_1_1_1_'></a>[https://numpy.org/doc/stable/user/how-to-partition.html](#toc0_)
###### <a id='toc1_1_1_1_1_2_'></a>[https://numpy.org/doc/stable/user/basics.creation.html](#toc0_)

### <a id='toc1_1_2_'></a>[Create arrays with regurlarly space values](#toc0_)

#### <a id='toc1_1_2_1_'></a>[1D domains](#toc0_)

##### <a id='toc1_1_2_1_1_'></a>[linspace vs. arange](#toc0_)

* Both numpy.linspace and numpy.arange provide ways to partition an interval (a 1D domain) into equal-length subintervals. 
* These partitions will vary depending on the chosen starting and ending points, and the step (the length of the subintervals).
    * Use numpy.arange if you want integer steps.
    * Use numpy.linspace if you want the endpoint to be included in the result, or *if you are using a non-integer step size.*


In [3]:
# np.arange(start, stop, step)
np.arange(0, 10, 2)  
# array([0, 2, 4, 6, 8])

array([0, 2, 4, 6, 8])

In [4]:
# np.linspace(start, end, quantity)
np.linspace(0.1, 0.2, num=5)
# array([0.1  , 0.125, 0.15 , 0.175, 0.2  ])

array([0.1  , 0.125, 0.15 , 0.175, 0.2  ])

In [5]:
# np.linspace(start, end (not included), quantity)
np.linspace(0.1, 0.2, num=5, endpoint=False)
# array([0.1, 0.12, 0.14, 0.16, 0.18])

array([0.1 , 0.12, 0.14, 0.16, 0.18])

### <a id='toc1_1_3_'></a>[Create arrays with random values](#toc0_)
###### <a id='toc1_1_3_1_1_1_'></a>[Random sampling (numpy.random)](#toc0_)
###### <a id='toc1_1_3_1_1_2_'></a>[https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random](#toc0_)
###### <a id='toc1_1_3_1_1_3_'></a>[https://numpy.org/doc/stable/reference/random/generator.html](#toc0_)

### <a id='toc1_1_4_'></a>[1D domains](#toc0_)

In [6]:
# Object generation - Create an objet of class random to generate random numbers
rng = np.random.default_rng()

In [7]:
# generate one random number
onerandom = rng.random()

# generate random numbers 
tenrandom = rng.random(10)

# ten random numbers inside a normal (gaussian) distribution.
tengaussianrandom = rng.standard_normal(10)

# print random numbers
print("one random:", onerandom)
print("ten random:", tenrandom)
print("ten random with normal distribution:", tengaussianrandom)


one random: 0.36923579641880044
ten random: [0.43748514 0.04670317 0.99047526 0.56992933 0.07012299 0.88721504
 0.18275163 0.8961204  0.05258189 0.36788637]
ten random with normal distribution: [-0.21498161  1.57531635  0.00888367 -0.79416495 -2.47263728  2.43361184
  0.98236768 -0.85156133  0.06541448 -1.92266432]


In [8]:
# seeds: np.random.defoult(seed) makes repeat the result
rng = np.random.default_rng(12345)
rints = rng.integers(low=0, high=10, size=3)
rints # play this snippet several times

array([6, 2, 7], dtype=int64)

In [9]:
# no seeds: np.random.defoult(seed) makes repeat the result
rng = np.random.default_rng()
rints = rng.integers(low=0, high=10, size=3)
rints # play this snippet several tims

array([5, 8, 9], dtype=int64)

In [10]:
# genrate 10 random numbers between 0 and 100
# imagine that is the age of people
rng = np.random.default_rng(12345)
ages = rng.integers(low=0, high=100, size=10)
ages

array([69, 22, 78, 31, 20, 79, 64, 67, 98, 39], dtype=int64)

In [12]:
# genrate 10 random numbers between 100.000 and 1.000.000
# imagine that is the salary of people
rng = np.random.default_rng(12345)
salary = rng.integers(low=100000, high=1000000, size=10)
salary

array([729293, 304602, 809782, 385082, 283759, 817628, 678415, 708629,
       989610, 451998], dtype=int64)